In [1]:
import pandas as pd

df = pd.read_csv('balance_hist_anon.csv', index_col=0)
df.index.name = 'id'
df

/Users/joe/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:472: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

,EBIZ_BALANCE_ID,VALID_FROM,VALID_TO,GIRONUMBER,AMOUNT,CURRENCY
id,,,,,,
0,208724450,2017-04-14 22:24:01.683,2017-04-14 22:26:07.497,1170008-00543226,7.060565e+08,HUF
1,208724451,2017-04-14 22:24:01.683,2017-04-14 22:26:07.497,1170945-03286018,1.601980e+03,USD
2,208724452,2017-04-14 22:24:01.683,2017-04-14 22:26:07.497,1170945-03286881,6.926736e+04,EUR
3,208724453,2017-04-14 22:24:01.683,2017-04-14 22:26:07.497,1170008-00546085,1.509114e+08,HUF
4,208724454,2017-04-14 22:24:01.683,2017-04-14 22:26:07.497,1170008-00545998,1.527115e+08,HUF
...,...,...,...,...,...,...
6427311,538436575,2020-07-31 14:28:51.530,2020-10-26 11:45:54.447,11702111020055198,1.196163e+06,HUF
6427312,538436694,2020-07-31 14:28:51.530,2020-10-26 11:45:54.447,11702245020068310,4.230240e+05,HUF
6427313,538436936,2020-07-31 14:28:51.530,2020-10-26 11:45:54.447,11702036020696850,9.230003e+06,HUF
6427314,538436937,2020-07-31 14:28:51.530,2020-10-26 11:45:54.447,11702033022816896,1.848733e+06,HUF
6427315,538437082,2020-07-31 14:28:51.530,2020-10-26 11:45:54.447,11702003020130721,5.810147e+06,HUF

2 reasons why only small part is used: 
1. smaller dataset - easier testing
2. number of rows can be increased instead of resetting offset

In [2]:
df.head(15000).to_csv('data/balance.csv', index=True)